version: '2'
services:
    nginx-service:
        build: ./requirements/nginx
        restart: always
        depends_on:
            - wordpress-service
        image: nginx-image
        networks: 
            - docker-network
        volumes:
            - wp-static:/www/
        ports:
            - 80:80
            - 443:443
    db-service:
        build: ./requirements/mariadb
        restart: always
        image: mariadb-image
        networks: 
            - docker-network
        volumes:
            - dbdata:/var/lib/mysql
        env_file: .env
    wordpress-service:
        build: ./requirements/wordpress
        restart: always
        depends_on:
            - db-service
        image: wordpress-image
        networks: 
            - docker-network
        volumes:
            - wp-static:/www/
        env_file: .env
    adminer:
        build: ./requirements/bonus/adminer
        restart: always
        networks: 
            - docker-network
    cv:
        build: ./requirements/bonus/cv
        restart: always
        networks: 
            - docker-network
networks: 
    docker-network:
volumes:
    dbdata:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/trouchon/data/database'
    wp-static:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/trouchon/data/wordpress'